### ISSUE TITLE
Review hash constructions

### ISSUE THREAD

**Issue by nemothenoone** [NilFoundation/hash#10]
Review of Merkle-Damgard, Sponge, HAIFA constructions would be required to make sure it is implemented correctly.

Particular problems an implementer could face:
* For now there are construction-specific data stream processors, which confronts the architecture. Every stream processor should be construction and accumulator-agnostic, so this possibly would lead to unification of stream processors with Block Cipher's ones.
* No insurance is made about implementation correctness of HAIFA and Sponge constructions.

**Comment by nkaskov** [comment]
Bits calculations in accumulators/hash.hpp look very bad.

**Comment by nkaskov** [comment]
It is necessary to make merkle-damgard construction digest function being able to work not only with big-endian format @a1falcon

**Comment by nkaskov** [comment]
[Old] We had this one:

```
template<>
void append_length<0>(block_type &block, length_type length) {
}
```

in
https://github.com/NilFoundation/hash/blob/master/include/nil/crypto3/hash/detail/merkle_damgard_construction.hpp

Because of this, we were getting "explicit specialization in non-namespace scope" while the compilation.

Fixed with: 
6f7a7e8
d03688f

**Comment by nkaskov** [comment]
Endianness-related util functions must be separated from construction and accumulator code.

**Comment by nkaskov** [comment]
It was decided to move all the endianness-related util functions to detail namespace.

**Comment by a1falcon** [comment]
Blake2b hash just pads last block with zeros if needed during finalization step, so in case of full block no zero bits will be added. Current accumulator architecture works in a way that it processes the block immediately when the cache is filled up with necessary amount of data. Therefore, in construction at the moment of finalization the cache is already empty, and hence, the full-block case cannot be handled properly.

**Comment by nkaskov** [comment]
It's necessary to write tests for all the completed hashes:
- BLAKE2b
- MD4
- MD5
- RIPEMD
- SHA
- SHA1
- SHA2
- SHA3
