### ISSUE TITLE
Unsigned and size_t hash params

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/hash#18]
Perhaps we need to choose the type of hash parameters. They must be either unsigned or size_t. As far as I can see, now we have some confusion on this matter.

**Comment by nemothenoone** [comment]
It seems to me reasonable choice would be ```std::size_t``` because of such a type is already widely used in params definitions.

**Comment by nkaskov** [comment]
Yes, I also think it would be better to use size_t.

**Comment by nkaskov** [comment]
Duplicate of #6 and #11
