### ISSUE TITLE
Formalize pack description

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/hash#35]
Pack is a quite difficult thing. Thus we need to formalize its description and requirements for future usage and modification.

**Comment by nemothenoone** [comment]
Em, not sure such an utility piece of code matters something in terms of concepts. Concepts are supposed to be an architectural trick, named type requirements to use them in some generic algorithm type traits. Packing is important, but it is an algorithm itself. Type requirements are not applicable here, I think.

**Comment by nkaskov** [comment]
OK, maybe not a concept. But we should formalize what we expect from pack now while we are reviewing it. Otherwise, we'll waste a lot of time understanding it next time.

**Comment by nemothenoone** [comment]
Agreed. Extremely descriptive comments along with inclusion into the doxygen-generated documentation would do the trick, I believe?

**Comment by nkaskov** [comment]
Yes. I think that will work.
